development:
  type: mysql
  host: localhost
  port: 3306
  database: wearables
  user: wearables
  password:
  
production:
  type: mysql
  host: localhost
  port: 3306
  database: wearables
  user: wearables
  password:
