Aisha:
  - Alien
Chia:
  - Apple
  - Asparagus
  - Aubergine
  - Avocado
  - Blueberry
  - Carrot
  - Chokato
  - Coconut
  - Durian
  - Garlic
  - Gooseberry
  - Grape
  - Lemon
  - Lime
  - Pea
  - Peach
  - Pear
  - Pepper
  - Pineapple
  - Plum
  - Thornberry
  - Tomato
  - Onion
Grundo:
  - Mallow
Poogle:
  - Msp
Quiggle:
  - Quigukiboy
  - Quigukigirl
Usul:
  - Usukiboy
  - Usukigirl
